spring:
  application:
    name: @project.artifactId@
  profiles:
    active: nacos
  main:
    allow-circular-references: true
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB      # 单个文件最大 500MB
      max-request-size: 500MB   # 整个请求最大 500MB
      file-size-threshold: 2MB  # 超过 2MB 写入磁盘
  # 数据源配置
  datasource:
    url: jdbc:mysql://192.168.2.102:3306/test?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 154347188@qq.com
    password: gmvniasmudylbhbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # 开启 SQL 日志
  global-config:
    db-config:
      id-type: auto  # 主键自增
      logic-delete-field: isDeleted  # 逻辑删除字段
      logic-delete-value: 1  # 已删除
      logic-not-delete-value: 0  # 未删除
